// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'attributeModal': string;
  'checkItem': string;
  'cusMoveTableBox': string;
  'dropDownContainer': string;
  'dropDownItem': string;
  'foo-animation': string;
  'fooAnimation': string;
  'hiddenDrop': string;
  'tableBtnBox': string;
  'tableBtnBoxLeft': string;
  'tableBtnBoxRight': string;
  'tableTitle': string;
  'tableTitleResizeRight': string;
  'tableTitleResizeRightLast': string;
  'wordMask': string;
}
export const cssExports: CssExports;
export default cssExports;
